### ISSUE TITLE
Archive DB

### ISSUE THREAD

**Issue by nbeard49** [Kurtsley/SeedArchive#12]
Is it necessary to maintain a separate archivecrops.db file if we're going to be leveraging backups tied into this program?
I would think that using a separate branch for DB testing and then backing up the original DB to reference if needed would be all that's required here. If we add SAVE/RESTORE options to the program I would think that maintaining a single master DB file would be fine.

**Comment by Kurtsley** [comment]
Good point, merging them makes sense now. I talked to him and he said with the history function a daily backup isn't necessary. Just have the database file and one backup mirrored at all times if possible.
