### ISSUE TITLE
Confirmation of SQL statements

### ISSUE THREAD

**Issue by Kurtsley** [Kurtsley/SeedArchive#18]
I would like each action in SQL to be confirmed somehow.

**Comment by nbeard49** [comment]
This will really only be needed for the INSERT statements in the 'add_entry' and 'add_to_archive' functions since the UPDATE statements would reflect immediately on the GUI correct?

**Comment by nbeard49** [comment]
I don't think this is necessary as we already have error handling in place and the documentation I'm looking at says that INSERT statement errors will throw an exception.
