### ISSUE TITLE
Excel table conversion program

### ISSUE THREAD

**Issue by Kurtsley** [Kurtsley/SeedArchive#37]
Need to get the latest data from Justin and convert it to a new set of databases. Would be nice to do this automagically.

**Comment by nbeard49** [comment]
Python can do csv imports via excel with the csv module...

**Comment by Kurtsley** [comment]
True, it was a little more complicated when I did it the first time though. Columns had to be removed and crap, it was late at night. Unfortunately I didn't keep the code around.

**Comment by Kurtsley** [comment]
Make sure to change the date edited column to fix the null values when this happens.
