### ISSUE TITLE
Date edited sorts wrong when more than one change made per day

### ISSUE THREAD

**Issue by Kurtsley** [Kurtsley/SeedArchive#57]
The newest entries appear at the bottom when you make more than one change a day. Maybe could add hours and minutes to date edited.

**Comment by Tractor107** [comment]
If this is issue that appears in the History, it still occurs. Not sure if anything can be done. If we add hours and minutes to the "date edited", could we somehow hide it on the GUI so that it isn't seen, but still there performing a function?

**Comment by Kurtsley** [comment]
Will probably have to do exactly that.
