### ISSUE TITLE
Backup System

### ISSUE THREAD

**Issue by Kurtsley** [Kurtsley/SeedArchive#7]
Need a backup system to save the databases every shutdown. Probably marked with the current date. Also need the ability to open those files in the program.

**Comment by nbeard49** [comment]
I'll work on this as it should be as simple as having a backup function that is run prior to graceful program exit. That would lock/dump the DB and append a date/timestamp for reference in a separate 'backups' directory under the current assets folder.

Are you fine with manual DB restores via the filesystem (delete / rename if necessary) or are you going to integrate SAVE/RESTORE DB menu items in the GUI? I'm just wondering if this should be split into separate functions where db_save could be called on that menu selection and automatically on program exit, and db_restore could be called based on the menu selection to take arguments for the DB file to restore (or to list and allow selection).

**Comment by Kurtsley** [comment]
I guess the previous closed issue solved some of this. Just one mirrored database alongside the main one.
